---
- name: change server port 000-default.conf
  copy: src=000-default.conf dest=/etc/apache2/sites-available/000-default.conf
- name: change server port ports.conf 
  copy: src=ports.conf dest=/etc/apache2/ports.conf
- name: restart apache2
  service: name=apache2 state=restarted
